### ISSUE TITLE
Add support to `QuantumCircuit` and `DAGCircuit` methods involving `Expr` expressions

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit-terra#10233]
### What should we add?

This forms a lot of the work needed for actual use of [the initial classical-expression design document](https://github.com/Qiskit/RFCs/blob/master/0010-simple-classical-representations.md).

Depends on #10223 and #10224.

```[tasklist]
### Contained issues
- [ ] #10226
- [ ] #10227
- [ ] #10230
- [ ] #10231
- [ ] https://github.com/Qiskit/qiskit-terra/issues/10359
- [x] https://github.com/Qiskit/qiskit-terra/issues/10379
- [x] https://github.com/Qiskit/qiskit-terra/issues/10380
```

~In addition to the `DAGCircuit` methods that are explicitly called out above, I `substitute_node_with_block` and `substitute_node` both technically need updating with support for `Expr` values.  _However_, I think in practice that these operations do not make sense in the same way with control flow, and since we need to rework how the `DAGCircuit` data structure works with control flow anyway, I don't think they will actually need touching.~

*edit*: in having done this, I think it's actually simple enough and meaningful to define the behaviour for `substitute_node_with_dag` and `substitute_node`, and likely will be useful for PRs in the vein of #9580.

**Comment by jakelishman** [comment]
As of right now, the PRs:
- #10362
- #10375 
- #10377 
- #10383 
- #10367 
- #10381 
- #10380 

close every issue in this task list.  Once the task list is complete, this issue can be closed as completed.

**Comment by jakelishman** [comment]
All contained issues now closed.
