### ISSUE TITLE
Refactor circuit library to not subclass `QuantumCircuit`

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#12293]
### What should we add?

For qiskit 2.0 it would be good to refactor the circuit library to be a collection of circuit construction functions rather than `QuantumCircuit` subclasses. At the end of the day the majority of the classes in the circuit library are just using the constructor to build a `QuantumCircuit` and returning themselves and not specializing the circuit class. Moving to a function that returns a `QuantumCircuit` object will remove a layer in the type hierarchy and also make it clearer that the classes are just circuits. It also will make rust implementations of these functions easier after #12205 merges.

The one exception are the `BlueprintCircuit` classes. These try to adjust the internals of the `QuantumCircuit` to make them dynamically build (or rebuild/reconstruct if the properties change) based on provided properties. However, this functionality is not necessary anymore and it adds a lot of complexity to the classes that use it.

- [x] Add equivalent circuit construction functions for all the circuit classes and use them internally for `__init__` (in non-`BlueprintCircuit` classes).
- [x] Deprecate the circuit classes and point to the new functions
- [x] Deprecate `BlueprintCircuit`
- [ ] In Qiskit 2.0 remove all the `QuantumCircuit` subclasses in the circuit library.

**Comment by Cryoris** [comment]
This has been done for 2.0, though we only deprecated the `QuantumCircuit` subclasses due to their heavy use and decided to only remove them for 3.0. It might be good to keep this issue though to remember deleting the deprecated objects for v3.0.
