### ISSUE TITLE
DAG needs to be refactor

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1912]
One of the groups in Qiskit Camp was focused in improving the our current DAG. A lot of small issues accumulated around DAG and it's time for a big refactor to balance out the technical debt here:
 - Support DAGNodes objects (#1851)
 - A well-define DAG API:
   - We are accessing the internal multi-graph sometimes (it's better after PR #1897).
   - Some transformation are happening in place that should be modified to get "new" DAGs.
 - A new and simpler internal representation of the DAG
   - Networkx is slow for our usage.
   - A simpler internal DAG will allow us to focus on good performance on the operations that we do more often (like, append at the end)
 - We want to remove named quantum registers from the internals of the DAG: They add complexity and a performance penalty when compared.
 - We need to distinguish between gates and instructions.

In general, this is the plan:
- [ ] Symbol table / optional labels
- [x] Define a new API with the new structure in mind https://github.com/Qiskit/qiskit-terra/issues/728#issuecomment-471074045
   - The only in-place change is to add things
   - Return fresh DAGs
- [ ] Remove access to the internal structure
   - [ ] qiskit/tools/visualization/_dag_visualization.py
   - [ ] qiskit/tools/visualization/_utils.py
   - [ ] qiskit/converters/dag_to_circuit.py
- [ ] Replace the underlaying structure
   -  Remove networkx
   -  Easy to add at the end
   -  For other cases, return new DAG
- [ ] DAGNode Objects
   - Node id should not part of it.
- Small optimizations
   - Delayed removal
   - numpy internal use for continue memory array?
   - `__slots__` for DAGNodes?

I will try to focus exclusively on this on the coming days because it's a change that will touch many things. So, it will probably happen soon. I'm touching base with @ajavadia to keep it align with the broad goal and @boschmitt is the main driving technical force in this effort.

**Comment by mtreinish** [comment]
Closing this as not relevant anymore. Most of the things listed here have already been done or aren't really relevant anymore. Especially a lot of the performance and optimization things were addressed by moving to retworkx andother tuning. If there are any outstanding things in the DAGCircuit api we need to cleanup we can open that in a separate issue
