### ISSUE TITLE
Defaults schema

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#1926]
### What is the expected enhancement?
With the new `defaults` endpoint for pulse a new schema implementation will be required. These are detailed on [pg.33 of the openpulse specification] (https://arxiv.org/pdf/1809.03452.pdf). 

- [x] `qubit_freq_est`
- [x] `meas_freq_est`
- [x] `buffer`
- [x] `pulse_library`: Will be part of schedules that are part of `CommandDefinition`.
- [x] `cmd_def`: `CommandDefinition` object will be dynamically built #1918 
- [x] `meas_kernel`: Will be of type `Kernel` see #1901 
- [x] `discriminator`: Will be of type `Discriminator` see #1901.

**Comment by taalexander** [comment]
Closed via #1757.
