### ISSUE TITLE
Standard pulse library

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#1937]
### What is the expected enhancement?
A collection of standard libraries for pulse experiment design.
- [x] pulse function library (#1933)
- [x] sampling strategy library (#1935)
- [ ] pulse filtering library (#1936)
- [ ] data analysis library
   - [x] signal processing
   - [ ] kerneling
   - [x] discrimination

**Comment by lcapelluto** [comment]
Kerneling is blocked on having available devices which return raw data

**Comment by 1ucian0** [comment]
Is this still blocked?

**Comment by taalexander** [comment]
All issues that will be solved have now been solved so closing.
