### ISSUE TITLE
Jupyter notebooks and visualizations should be moved to a different package

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2521]
In the quest for lighting Terra, it seems to me that there is some consensus for moving notebooks [[1](https://github.com/Qiskit/qiskit-terra/pull/2047#issuecomment-482896732_), [2](https://github.com/Qiskit/qiskit-terra/issues/805#issuecomment-416537653)]
 (and the associated visualization tools [[3](https://github.com/Qiskit/qiskit-terra/issues/595#issuecomment-428776013)]) to a different repo/package, since they effectively are a layer on top of Terra.

The task associated with this are:
 - [ ] Confirm the consensus
 - [ ] Choose a name a create the repo/package
 - [ ] Move code, tests, and issues for:
   - [ ] Non-text visualizations associated with notebooks (circuit, city plots, etc)
   - [ ] Jupyter tools in `qiskit/tools/jupyter`

This will allow us to move towards a totally network-independent Terra, to reduce the noise associated with issues and PRs on the jupyter layer, and to light dependencies.

**Comment by mtreinish** [comment]
I don't think there is a consensus on this, and personally I think it's a really bad idea to remove the visualizations for all the same reasons I outlined in #595. Which is even more reinforced now because we've declared those interfaces as stable since 0.7. It's also a false premise that the mpl and latex visualizations are only used with jupyter, they're often used outside that context with just terra and python. The jupyter helpers in `qiskit.tools.jupyter` is different though and I'd be fine with spinning off if that's what people want to do. Since that's mostly self contained and not something we've said we were going to provide a stable interface for.

The network utilization in tests is something we can fix independently of removing pieces it is not isolated to jupyter usage. (see `qiskit.tools.monitor`) People do use those tools outside of jupyter today and that wouldn't be removed if we spun out the jupyter. Although arguably that should live in the ibmq provider not terra now that the IBMQ code lives in it's own module.

The interactive visualizations are different and actually completely untested. I actually don't know if anyone is using them. I'd be all for removing them mostly because of #805 and the being untested, except it's part of the published stable api. So, I'd vote for deprecation in 0.9 and removal in 0.11 (not 0.10 because I think a 2 cycle deprecation for things we've said our stable will give people enough time to migrate).

That all being said I do want to say that while splitting things out into yet another repo can seem like an attractive option, it causes a pain for our users. I don't think a day goes by where I don't have to work with someone who gets confused by the inter-tangled web of dependencies between just qiskit packages (not even considering external packages). Or the fragility of namespace packages going wrong and breaking in a weird way getting someone stuck. It might seem simple to us because we use things everyday, but the more complexity we put in just how we package subsets of functionality causes a lot of pain for end users.

**Comment by jaygambetta** [comment]
We are not splitting up anymore than we have -- it is already I bit too much. We can decided on this when we move to 1.0 but for now lets keep it moving forward with features.

**Comment by nonhermitian** [comment]
Yeah, this splitting is not going to happen anytime soon.  Visualizations are a key part of terra, used in basically every tutorial, presentation etc.  Also, feedback from users indicates that they features are some of the most popular parts of terra.

**Comment by ajavadia** [comment]
Since clearly there is not a consensus, I'm closing this issue. 

I also think visualizations should stay. Previously I suggested splitting the jupyter tools, but don't have a very strong opinion on it. I think if we end up adding visualization/jupyter tools that deal with let's say aqua, then that might be a reason to have a separate qiskit module for them. Right now they basically deal with terra elements.

**Comment by diego-plan9** [comment]
For what is worth, I agree with @1ucian0 and believe that moving that layer to another package is a sensible thing and hope it can be reevaluated at some point.

The move would not imply reducing the importance of visualizations, nor incur in changes to the stable interface - as a matter of fact, it would be pretty transparent and straightforward. We already have an example of that transition in the split of the `IBMQProvider`, which did contain similar implications (popular feature and stable interface) and was rather uneventful. 

With the risk of re-hashing older discussions, I think we should also throw into the mix the importance of a lean terra not only for 1.0, but for the present work in other areas. So basically +1 to @1ucian0 !

**Comment by dongreenberg** [comment]
Curious, what would the "leanness" from splitting do for us? Are any users complaining about the install size?

**Comment by dongreenberg** [comment]
@diego-plan9 @1ucian0 bump

**Comment by 1ucian0** [comment]
I dont remember any user complaining about that. It's mostly about testing time and responsibility separation.
