### ISSUE TITLE
Unify style across circuit visualizers

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#2797]
The circuit visualizers are currently configurable via some `kwargs` to the `circuit.draw()` function, but also the `mpl` drawer accepts a `style` dict. This request is to unify the interface so that the important ones are accessed via the kwargs. The mpl style should probably just be trimmed down to some coloring schemes.

Here's a rundown of the status of each:

- [ ] 'cregbundle': this is a useful option that is only available via the mpl style, and I'd like it to be available in all via a kwarg in `draw()`. PR #4274

- [x] 'line_length' kwarg: this currently only works for text. The mpl accepts a 'fold' key in its style. These should be consolidated into a `fold` kwarg (i think fold is better than line_length). PR #3108

- [ ] 'scale' kwarg: works well for mpl and latex. Does not work for text, which is probably expected. But docstring should reflect that. PR #4274

- [x] ~'filename' kwarg: file saving does not work for text. It should.~ Could not reproduce.

- [x] 'plot_barriers' kwarg: this works well. The mpl style key 'plotbarriers' is redundant and should be removed. PR #3105

**Comment by maxKenngott** [comment]
I'd like to give this one a shot if possible.

**Comment by 1ucian0** [comment]
Sure! Let me know if you need any help!

**Comment by 1ucian0** [comment]
@maxKenngott Probably the best way it to make a PR for each of the items in this issue. Are you going for any one in particular first?

**Comment by 1ucian0** [comment]
>  'plot_barriers' kwarg: this works well. The mpl style key 'plotbarriers' is redundant and should be removed.

Fixed in https://github.com/Qiskit/qiskit-terra/pull/3105

**Comment by 1ucian0** [comment]
I used a flight to attack some of them. Let me know what's in your plate @maxKenngott !
