### ISSUE TITLE
follow up to ControlledGate implementation

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#3453]
follow up to #2862:

- [x] write release notes (#3465)
- [x] delete unused imports in `test/python/circuit/test_controlled_gate.py` (PR #3487)
- [x] add `circuit.to_gate()` shorthand  (#3455)
- [x] replace `q_if` with `control` (#3455)
- ~[ ] bug: cannot get `gate.to_matrix()` for a gate obtained from `instruction_to_gate(circuit_to_instruction(circ))`~
- [x] bug: `base_gate` is a class, not an object, so it throws away the params (done in PR #3454)
- [ ] the optimize_1q_gates should be able to handle optimizations where the chain of single-qubit gates are controlled by the same control lines

**Comment by 1ucian0** [comment]
Closing this issue since the last bullet is tracked by #3563
