### ISSUE TITLE
Complete the Jobs implementation

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-terra#539]
## Description

Complete the implementation of `Job`s.

## Checklist

* [x] allow to retrieve jobs from the API that were launched in another session #501
* [x] increase robustness of local job tests #526 
* [x] increase robustness of remote job tests #515
* [x] allow cancelation of jobs? #638
* [ ] test when backend support is ready

## See also

#413: previous issue with 0.5 planning

**Comment by delapuente** [comment]
AFAIK, cancelling jobs is [already implemented](https://github.com/QISKit/qiskit-core/blob/master/qiskit/backends/ibmq/ibmqjob.py#L72-L95). Are we waiting for something else?

**Comment by ewinston** [comment]
@delapuente currently cancelling jobs only works with hubs.

**Comment by delapuente** [comment]
This should automatically work when the backend implements the functionality.
