### ISSUE TITLE
Improve user authentication handling (QConfig)

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-terra#540]
## Description

Improve the current `QConfig.py` based authentication system in order to simplify the usage for the regular user flow (ie. when using `qiskit-core` as a single-account application) while retaining flexibility for other scenarios and user preferences.

## Proposed implementation

Following the discussions at #385 and #471:
* provide a "transparent loading of user configuration" that looks for the configuration in default places:
  * a file based on the user home folder (`.qiskit/qiskit.rc` or similar)
  * environment variables
  * the current folder? (for compatibility purposes)
  This should only be invoked when using `register()`, possibly by making the parameters for this function optional.
* provide a simply helper script for generating the configuration file for the first time (ideally for updating it as well).
* update the documentation accordingly, placing emphasis on transitioning from `QConfig.py` to the new system.

## Checklist

* [x] implement the wrapper functionality. #547 
* [x] implement the helper script. #547 
* [x] update documentation (README, sphinx, docstrings). #547 
* [ ] update tutorials and other resources.

## See also

#413: previous issue with 0.5 planning

**Comment by tellison** [comment]
May I add a requirement here, described in #471, that the final mechanism is usable without having to modify any parts of the QISKit installation?

In scenarios such as Cloud or containers usage it my not be permitted to modify the installation location, so it must be possible to configure the library externally.  This might include an API call to define the source of the user configuration file, environment vars, and so on.

While a helper script to generate a configuration can be useful for single user install on a dedicated machine, it typically won't be usable in this scenario.

**Comment by diego-plan9** [comment]
Absolutely - that would be one of the design goals, which is two-fold:
* for the most common use case (which assumes access to files, etc - can be roughly described as "an user interested in running circuits against an online backend from a regular machine"), to streamline the process and probably just have to invoke `register()` without extra parameters whenever access to the online resource is needed. We want to extend this common use case a bit more and also include support for environment variables, which I hope would help in your proposed scenario and others.
* for other use cases and users needing finer control over authentication (for the reasons you provided: in some environment it might be not possible or desirable to use files, etc, and for more complex usages), full control over the parameters passed to `register(token, url, ...)` will still be possible. This delegates the handling of "how the token is retrieved" to the logic on the user program that uses `qiskit`.

It was also not explicitly mentioned on the brief description, but for the configuration file, we would also make it possible to specify another location rather than the default ones (which I think might help in the specific case of container usage, where the paths might be more restricted). Would those mechanisms cover the requirement that you mention? We are open to more ideas!

**Comment by tellison** [comment]
I hope so.  At the moment I have a container with QISKit and the project's Jupyter examples in a format suitable for use by a variety of users.

I have to modify the QISKit install to move the `Qconfig.py.template` to `Qconfig.py` (which is ok, but not ideal), and once that is done I can use the `IBMQE_API` env var to inject the user-specific access key into the library as the notebooks are run.

This works well for the generic notebooks, and it sounds like you will maintain that flexibility in the redesign.  The additional flexibility for locating a configuration file, and passing the parameters to `register()` all sound good too, but won't be immediately useful to the example notebooks as we wouldn't expect people to change those to make them work.
