### ISSUE TITLE
Introduce and use QObj

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-terra#541]
## Description

Implement the `QObj` in `qiskit-core` as the format used for communication with the backends. Please note that for the full implementation to be completed, we need changes outside the core (online backends, api, etc).

## Checklist

* [x] add the schemas to the codebase #434 
* [x] introduce a `QObj` class, adjusting the existing codebase to use it (but keeping the original structure - mostly replace the `dict` with `QObj`) #589
* [x] update the local backends for using the `QObj` class #589
* [x] update the codebase for using the `QObj` schema #647
* [x] provide a converter that outputs the old schema, for the transition #648
* [ ] update the remote backends for using the `QObj` class and schema #649
* [x] introduce validation against the schemas #651

## See also

#676 For polishing efforts.
#413: previous issue with 0.5 planning
#283: discussion of qobj interface
#415: WIP for the QObj class - will be reissued with a simpler version

**Comment by ajavadia** [comment]
@diego-plan9: seems like the "proposed implementation" section of this belongs to another issue and is included here by mistake.

**Comment by diego-plan9** [comment]
> @diego-plan9: seems like the "proposed implementation" section of this belongs to another issue and is included here by mistake.

Yes, thanks :grin:

**Comment by diego-plan9** [comment]
Updated the issue with two new sub-taks (#664 , #663 ).

**Comment by jaygambetta** [comment]
is this done for 0.6 @delapuente and @diego-plan9

**Comment by diego-plan9** [comment]
I think so - the only remaining item is already in its own issue ( #649) and it's basically for tracking (and after 0.6), so it makes sense to close this one. Thanks everyone for the big effort on introducing `Qobj`, it has been quite an accomplishment for the whole team :tada:
