### ISSUE TITLE
Implementation of a pulse schedule block

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#5679]
### What is the expected behavior?

Pulse `Schedule` doesn't support parameterization of `duration`  because it immediately evaluates the overlap of instruction over the channel `timeslots`. Here we implement new program representation called `ScheduleBlock` which consists of `transform_policy: Enum` and `blocks: List[Union[Instruction, ScheduleBlock]]`. The `transform_policy` represents one of transformation functions defined in `qiskit.pulse.transforms` and this transform is applied to underlying `blocks` when the schedule block is converted into `Schedule`. Because this new representation doesn't have explicit timeslot, it can involve instruction with parameterized duration, and the duration is assigned just before it is converted into schedule (i.e. lazy timeslot evaluation). The implementation of pulse builder is also updated to use this new representation. The `ScheduleBlock` has compatibility with the `Schedule` thus there is no usability impact by this update. In addition, `Schedule` will not be deprecated and coexist with `ScheduleBlock` in Qiskit Pulse.

This will be split into:

 - [x] Phase1: Remove timeslot dependency from `Instruction`
 - [x] Phase2: Add `Call` instruction to wrap an appended schedule component by `pulse.call`
 - [x] Phase3: Implement `ScheduleBlock`
 - [x] Phase4: Update pulse builder implementation
