### ISSUE TITLE
VQE and Optimizer refactoring

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#6381]
### Summary

Refactor the VQE and the Optimizers according to [the design doc](https://gist.github.com/Cryoris/da034f29d76ced79f3f3e9d3d9e0af6c).

### Details

This refactor entails at least
- [x] Making VQE stateless (#6380)
- [x] Refactoring the Optimizer interface to use `minimize` (#6382)
- [x] Allowing callables as optimizers in VQE (#6383)

And optionally
- [x] Use parameter order of circuits instead of re-sorting by name in VQE (#5953, #5721)
- [x] Removing/Reducing `VariationalAlgorithm` to an interface (#6384)
- [x] Make Optimizers serializable (for usage with Qiskit Runtime) (#6385)
- [ ] Streamline VQE's interface by removing little used methods/arguments

**Comment by nonhermitian** [comment]
I think the difference still is that you are hiding functionality in the `VQE` class.  I guess the ask is that the end user be able to construct an entire variational problem using Qiskit building blocks without having to go through the class interface.  This enables ultimate flexibility and should not be too much work given that the functionality obviously exists internally, but is tied up in class interfaces.

**Comment by Cryoris** [comment]
I'm closing this since all items from the design doc concerning the VQE have been addressed. Also steppable optimizers are tackled in #8150.
