### ISSUE TITLE
Update all the backends for using the `QObj` and `Result` classes and schemas except device

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#649]
### What is the expected enhancement?
Adapt backends to consume the new `QObj` format and produce the new `Result` format.

- [x] test device understand and run qobj
- [x] test device return new format of result (according to result schema)
- [x] don't send qasm anymore just qobj, don't treat old result anymore (#754 -it's being addressed in #713 and must be on hold until completing all tasks above)
- [x] adapt `Result` API to the new backend result format (#756)
- [x] update the local python simulators for fully using `Qobj` (#663)
- [x] remote simulators consume qobj and generate new result (#831)

**Comment by ewinston** [comment]
Version 1.0.0 of qobj was run directly on a backend and appears to return results. Still to do is to more testing with a range of qobj input, complete setup of a queue on a test device, connect queue to front end.

**Comment by delapuente** [comment]
Since this is no longer tracking remote backends only, let's change the title to be more accurate.

**Comment by delapuente** [comment]
Changing the name since the scope of the issue has broadened to include adaptation to the new `Result` schema.

**Comment by delapuente** [comment]
Removing "update the local C++ simulators for fully using `Qobj` (#664)" since it has been moved out of 0.6.

**Comment by jaygambetta** [comment]
can this be changed to 0.7
