### ISSUE TITLE
Polish Qobj implementation

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#676]
### What is the expected enhancement?
After the merge of #589 and #655, there are some "internal cleanup" tasks to be performed:

- [ ] reduce the amount of verbosity when creating subclasses (long term, it should be possible to recreate them from the .json specs themselves), ideally preserving facilities for static analysis and clarity for the user #654
- [x] update the tests so the `QObj`s built into them are not created from a dictionary #650
- [ ] revise the `from_dict` and `as_dict` methods, as they are currently mostly a convenience for the transition #652
- [x] add more tests about the `QObj` class itself #653
