### ISSUE TITLE
Refactoring the compilation flow

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#704]
### What is the expected enhancement?

Subtasks to clean up the compilation flow, make it more modular, parallelize it, etc.

 - [x] Separate Circuits from DAGs from Qobj, only work with dags in the transpile (PR #705).
 - [x] Make sure dag has all the fields that circuits have so circuits don't need to be passed around (PR #705).
 - [x] Improve the pass-based transpiler to support advanced functionality (Issue #825, PR #824 )
 - [x] Remove the other output formats of transpile and only support dag (#1129)
 - [x] make sure transpile only uses pases. (#1161)
 - [x] Think about whether we want compilation of a batch where `coupling_map`, `basis_gates`, or `initial_layout` are different for each circuit. -- decided only one for batch.
 - [x] Swap mapper pass (PR #757)
 - [x] Unroll pass
 - [x] Rotation merge pass 
 - [x] A* mapper pass (Issue #750)
 - [x] Tree search swap mapper pass (pr #1140 )
 - [x] Choose Layout pass (#1499)
 - [ ] KAK decomposition pass (converting to single issue)
 - [x] There are two seeds that do different things (simulator seed, optimizer seed and should not be the same)
- [x] Remove `hpc` parameters from `transpile()` (Issue #769)
 - [x] Use a single standard for intitial_layout all the way down.
 - [x] Make using_qiskit_level_2 and 3 work correctly by allowing compile once/execute twice on different backends and to show how to customize circuits with transpile

**Comment by jaygambetta** [comment]
@ajavadia can you post the standard we are going to have for the intital_layout here so that we have a reference.

**Comment by ajavadia** [comment]
We decided to alter the format of the `initial_layout` to something like this:
```
[('q0', 0), ('q1', 0), None, ('q1', 1), ('q0', 0)]
```
where each tuple specifies one *circuit* qubit, and each position in the list corresponds to a physical qubit on the chip (in this case 5 qubits). The physical qubits are assumed to be ordered (Qobj has this assumption too).

This will hopefull have the flexibility of the current dictionary approach, but much easier to write (which was the goal of #727).

**Comment by jaygambetta** [comment]
Great i want to make sure this is taken all the way though.

**Comment by jaygambetta** [comment]
updated the top. We have decided that in batch mode coupling_map, basis_gates, initial_layout (maybe we change name to desired_layout) will not be customizable in compile. We will write an using qiskit to show how using transpiler.

**Comment by ajavadia** [comment]
Closing as most are done and the remaining ones have separate issues.
