### ISSUE TITLE
[EPIC] Introduce Jupyer notebook tools

### ISSUE THREAD

**Issue by atilag** [Qiskit/qiskit-terra#707]
### What is the expected enhancement?
One of the most demanded use-case in Qiskit is programming Jupyter notebooks, so it would be great to start thinking about including tools that can be exploited by our users to enhance their notebook programming experience.
If you want to propose a new feature, please create a comment in this very issue and once is accepted it will be added to the list below:

## Checklist

- [ ] Progress bar for compilation (#708)
- [ ] Magic function for checking the status of jobs. (#742)
- [ ] Show interactive visualizations in Jupyter.

**Comment by jaygambetta** [comment]
Do we need this now we have a project just for tools

**Comment by nonhermitian** [comment]
Depends on how strong we want to push the jupyter tools

**Comment by jaygambetta** [comment]
i want to track them individually in the project rather than global. But i let @mtreinish decide.

**Comment by mtreinish** [comment]
I'm going to close this since we have a tools.jupyter directory and those tools are all present (and we're building new ones now)
