### ISSUE TITLE
Clean up test suite, deprecated code, FIXMEs

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#725]
In preparation for the 0.6 release, some housekeeping items:

- [x] Fix places where running tests give warnings (PRs #719, #722, #723 )
- [x] Remove quantum program and its tests (PR #724)
- [ ] Update API to match Qiskit
   - [ ] `available` -> `operational` in `backend.status`
   - [ ] Remove lots of `FIXME` hacks in `ibmqbackend.py` (related to backend names, configuration, etc.)

These are non-blocking for the release, but nice to have.

**Comment by diego-plan9** [comment]
Actually, we have a couple of  methods in the wrapper (`local_backends` and `remote_backends`) that are [marked for deprecation](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/wrapper/_wrapper.py#L194). Can we check if this is a good time to fully remove them?

**Comment by ajavadia** [comment]
@delapuente yes looks good.
@diego-plan9 yes good time to remove those too. I'll do those in a PR i'm submitting.

**Comment by ajavadia** [comment]
Closing as this is basically done from the Qiskit side, now we have to wait for the API to update. Then we can go in and remove all the FIXMEs in `ibmqbackend.py`.
