### ISSUE TITLE
Complete transition to schema-conformat Qobj

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#851]
Adding validation against the Qobj schema (#651) to the JSON payloads submitted to the backends revealed that Qiskit is producing non-conformant Qobj instances. In particular, Qiskit still does not use the `bfunc` instruction for boolean conditions and does not implement any extension mechanism. To fully use Qobj, Qiskit should:

- [ ] Provide a Qobj backend to produce schema-conformant outputs. (#852 )
- [ ] When sending the Qobj to the backends, after converting to the old format, restore conditionals using the new `bfunc` to the old format using the `conditional` field. (#852)
- [ ] Implement Qobj double validation against general Qobj schema and backend-specific schema. (#871)

We also need to provide some extension mechanism to produce the proper Qobj for instruction extensions such as `snapshot`:

- [ ] Implement a mechanism for extending the synthesis of Qobj with new backend-specific instructions (#905)

**Comment by delapuente** [comment]
See the status of #861 before sending `bfunc` instructions to backends.

**Comment by diego-plan9** [comment]
Closing the issue after conversations with @jaygambetta , as we have probably diverged a bit from the plans about specs as a whole since the creation of the issue. In particular, having a generic mechanism for extending the specs (ie. not specific to the implementation in terra, but wider scope) appears to be less critical currently, and if needed it might be just easier to restart the attempt in another issue, with a fresh approach.
