### ISSUE TITLE
Migrate to `Target` as only backend input for transpiler passes

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#9256]
### What should we add?

Right now we have a mix of the legacy approach to modeling a backend in the transpiler (`basis_gates`, `CouplingMap`, etc) and the new approach, the `Target` class. This causes friction when adding new passes or maintaining existing ones because we have to support dual paths for everything. We unify all of the internals on the new model because in almost every case we can convert from the legacy model to the target without issue.

- [ ] Add support for `Target` to all transpiler passes that need backend constraints (even if it's just to get a legacy view, like a `CouplingMap` from the target)
    - [ ] #7113 tracked a subset of passes
- [ ] Document that moving forward all new passes only will get a `Target` (both contributor guidelines along with preset pass managers)
- [ ] Update preset pass manager construction to only pass a `Target` to passes
    - Stage plugins initialization will need to fill out all the fields in the `PassManagerConfig`  from the `Target` for backwards compatibility. We can stop doing this as we deprecate non-target constraint fields in `PassManagerConfig`
- [ ] Update `transpile()` to convert `BackendV1` inputs to `BackendV2` with `BackendV2Converter`
- [ ] Update `transpile()` to convert loose input of constraints to a `Target` with `Target.from_configuration()`
    - [ ] constructor added in: https://github.com/Qiskit/qiskit-terra/pull/9255
- [ ] Deprecate anything we previously could represent that is lost in conversion to `Target` (or alternatively augment `Target`'s data model to support these edge cases). The cases currently known where we're unable to convert from the legacy model to the `Target` are:
    -  `coupling_map` without `basis_gates` (represent solely a connectivity constraint).
    
After the above is done and released then we can start the deprecation process for the legacy inputs to the transpiler passes along with the `PassManager` config.

**Comment by wshanks** [comment]
I am trying to understand what the end state is here, based on the description and looking at #12850. I was surprised that #12850 does not deprecate `coupling_map`, `basis_gates`, or `dt`. Is it planned that it will remain possible to pass those parameters to `generate_preset_pass_manager` with or without a `Target`? I can see how it could be convenient to pass them rather than build a target but I don't see why it is necessary if the goal is to move everything to using a target.

**Comment by mtreinish** [comment]
@wshanks sorry we missed your comment here. The goal of this issue was to standardize our representation of QPU constraints inside the transpiler. Basically make it so that any pass that uses hardware constraints as part of it's operation that we give it only a target to represent those constraints from the preset pass managers.

We weren't trying to change the UI for the end user facing parts of the API but more just standardize how we work between the pass manager and individual passes. People (myself included) like to be able to shorthand `transpile(qc, basis_gates=[..] coupling_map=cmap)`.

 Before this issue we had a random assortment of data types that were flowing between passes to represent the same backend and it made working with all of qiskit's built-in passes harder. The PR that closed this didn't remove those all inputs for backwards compatibility reasons as people run passes standalone, but from the preset pass managers we should only be giving a target to all the passes now.
