### ISSUE TITLE
Rethink the testing strategy to reduce continuous integration times

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#927]
### What is the expected enhancement?
Current merging strategy allows merging a branch when it is up to date with the `master` branch only. This causes the workflow when merging several PR to be as follows:

1. The first PR is merged. This triggers a build on the CIs: `master_build`.
2. A second PR got out-of-date with `master`.
3. Merge the second PR with `master`. This triggers another build on the CIs: `merge_build`.
4. Wait for `master_build` to finish.
5. Wait for `merge_build` to finish.
6. Merge the second PR. This triggers a build on the CIs: `master_build`...
7. ...

There is an important bottleneck in steps 4 and 5 due to the number and duration of the CI's jobs.

This is a draft of the initiatives I'm taking to improve these times trying to reduce the bottleneck.

- [x] On regularly-basis, focus on a target environment: Python 3.5 + Linux (#1072)
- [x] Limit testing the complete environment matrix to once per day. (#1072)
- [x] Find a way to highlight fails on the `master` branch (#926)
- [ ] Avoid running the same tests on the same code base more than once.
- [ ] Aggressively cache the testing environments so preparing them takes as less time as possible.
- [x] Run tests in parallel (#730)

**Comment by 1ucian0** [comment]
Maybe use the `failfast` option?
```
$ python -m unittest --help
...
-f, --failfast        Stop on first fail or error
...
```

**Comment by 1ucian0** [comment]
The running time of the tests is relatively low with respect to the queue times now. I think we an close this issue. Opinions @mtreinish @diego-plan9 ?

**Comment by diego-plan9** [comment]
I think the original description contained some ideas not only related to the running time of an individual job, but for the situation as a whole. Still, I do agree this issue has become rather stale and the individual job times don't play such a big part currently, and it makes sense to re-evaluate the situation in a new one if needed - so indeed closing.
